import vine from '@vinejs/vine'

const schoolGroupTypeEnum = vine.enum(['CITY', 'STATE', 'CUSTOM'] as const)

export const listSchoolGroupsValidator = vine.compile(
  vine.object({
    schoolChainId: vine.string().uuid().optional(),
    type: schoolGroupTypeEnum.optional(),
    page: vine.number().min(1).optional(),
    limit: vine.number().min(1).max(100).optional(),
  })
)

export const createSchoolGroupValidator = vine.compile(
  vine.object({
    name: vine.string().trim(),
    type: schoolGroupTypeEnum,
    schoolChainId: vine.string().uuid(),
    isAutoGenerated: vine.boolean().optional(),
    hasInsurance: vine.boolean().optional().nullable(),
    insurancePercentage: vine.number().min(0).max(100).optional().nullable(),
    insuranceCoveragePercentage: vine.number().min(0).max(100).optional().nullable(),
    insuranceClaimWaitingDays: vine.number().min(0).optional().nullable(),
  })
)

export const updateSchoolGroupValidator = vine.compile(
  vine.object({
    name: vine.string().trim().optional(),
    type: schoolGroupTypeEnum.optional(),
    schoolChainId: vine.string().uuid().optional(),
    isAutoGenerated: vine.boolean().optional(),
    hasInsurance: vine.boolean().optional().nullable(),
    insurancePercentage: vine.number().min(0).max(100).optional().nullable(),
    insuranceCoveragePercentage: vine.number().min(0).max(100).optional().nullable(),
    insuranceClaimWaitingDays: vine.number().min(0).optional().nullable(),
  })
)
