import type { HttpContext } from '@adonisjs/core/http'
import SchoolChain from '#models/school_chain'
import SchoolGroup from '#models/school_group'
import { createSchoolGroupValidator } from '#validators/school_group'
import AppException from '#exceptions/app_exception'
import SchoolGroupTransformer from '#transformers/school_group_transformer'

export default class CreateSchoolGroupController {
  async handle({ request, response, serialize }: HttpContext) {
    const payload = await request.validateUsing(createSchoolGroupValidator)

    const schoolChain = await SchoolChain.find(payload.schoolChainId)
    if (!schoolChain) {
      throw AppException.notFound('Rede de escolas não encontrada')
    }

    const schoolGroup = await SchoolGroup.create({
      name: payload.name,
      type: payload.type,
      schoolChainId: payload.schoolChainId,
      isAutoGenerated: payload.isAutoGenerated ?? false,
      hasInsurance: payload.hasInsurance ?? null,
      insurancePercentage: payload.insurancePercentage ?? null,
      insuranceCoveragePercentage: payload.insuranceCoveragePercentage ?? null,
      insuranceClaimWaitingDays: payload.insuranceClaimWaitingDays ?? null,
    })

    return response.created(await serialize(SchoolGroupTransformer.transform(schoolGroup)))
  }
}
