import type { HttpContext } from '@adonisjs/core/http'
import SchoolChain from '#models/school_chain'
import SchoolGroup from '#models/school_group'
import { updateSchoolGroupValidator } from '#validators/school_group'

export default class UpdateSchoolGroupController {
  async handle({ request, params, response }: HttpContext) {
    const payload = await request.validateUsing(updateSchoolGroupValidator)

    const schoolGroup = await SchoolGroup.find(params.id)
    if (!schoolGroup) {
      return response.notFound({ message: 'Grupo escolar não encontrado' })
    }

    if (payload.schoolChainId) {
      const schoolChain = await SchoolChain.find(payload.schoolChainId)
      if (!schoolChain) {
        return response.notFound({ message: 'Rede de escolas não encontrada' })
      }
    }

    schoolGroup.merge({
      name: payload.name ?? schoolGroup.name,
      type: payload.type ?? schoolGroup.type,
      schoolChainId: payload.schoolChainId ?? schoolGroup.schoolChainId,
      isAutoGenerated:
        payload.isAutoGenerated !== undefined
          ? payload.isAutoGenerated
          : schoolGroup.isAutoGenerated,
      hasInsurance:
        payload.hasInsurance !== undefined ? payload.hasInsurance : schoolGroup.hasInsurance,
      insurancePercentage:
        payload.insurancePercentage !== undefined
          ? payload.insurancePercentage
          : schoolGroup.insurancePercentage,
      insuranceCoveragePercentage:
        payload.insuranceCoveragePercentage !== undefined
          ? payload.insuranceCoveragePercentage
          : schoolGroup.insuranceCoveragePercentage,
      insuranceClaimWaitingDays:
        payload.insuranceClaimWaitingDays !== undefined
          ? payload.insuranceClaimWaitingDays
          : schoolGroup.insuranceClaimWaitingDays,
    })

    await schoolGroup.save()

    return response.ok(schoolGroup)
  }
}
