import { BaseTransformer } from '@adonisjs/core/transformers'
import type SchoolGroup from '#models/school_group'
import SchoolChainTransformer from '#transformers/school_chain_transformer'

export default class SchoolGroupTransformer extends BaseTransformer<SchoolGroup> {
  toObject() {
    return {
      ...this.pick(this.resource, [
        'id',
        'name',
        'type',
        'isAutoGenerated',
        'hasInsurance',
        'insurancePercentage',
        'insuranceCoveragePercentage',
        'insuranceClaimWaitingDays',
        'schoolChainId',
        'createdAt',
        'updatedAt',
      ]),
      schoolChain: SchoolChainTransformer.transform(this.whenLoaded(this.resource.schoolChain)),
    }
  }
}
