/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type AcademicPeriodTransformer from '#transformers/academic_period_transformer'
import type AchievementTransformer from '#transformers/achievement_transformer'
import type AssignmentTransformer from '#transformers/assignment_transformer'
import type AttendanceTransformer from '#transformers/attendance_transformer'
import type CalendarSlotTransformer from '#transformers/calendar_slot_transformer'
import type CanteenItemTransformer from '#transformers/canteen_item_transformer'
import type CanteenMealReservationTransformer from '#transformers/canteen_meal_reservation_transformer'
import type CanteenMealTransformer from '#transformers/canteen_meal_transformer'
import type CanteenMonthlyTransferTransformer from '#transformers/canteen_monthly_transfer_transformer'
import type CanteenPurchaseTransformer from '#transformers/canteen_purchase_transformer'
import type CanteenTransformer from '#transformers/canteen_transformer'
import type ChallengeTransformer from '#transformers/challenge_transformer'
import type ClassTransformer from '#transformers/class_transformer'
import type CommentTransformer from '#transformers/comment_transformer'
import type ContractDocumentTransformer from '#transformers/contract_document_transformer'
import type ContractEarlyDiscountTransformer from '#transformers/contract_early_discount_transformer'
import type ContractInterestConfigTransformer from '#transformers/contract_interest_config_transformer'
import type ContractPaymentDayTransformer from '#transformers/contract_payment_day_transformer'
import type ContractTransformer from '#transformers/contract_transformer'
import type CourseHasAcademicPeriodTransformer from '#transformers/course_has_academic_period_transformer'
import type CourseTransformer from '#transformers/course_transformer'
import type EventParticipantTransformer from '#transformers/event_participant_transformer'
import type EventTransformer from '#transformers/event_transformer'
import type ExamGradeTransformer from '#transformers/exam_grade_transformer'
import type ExamTransformer from '#transformers/exam_transformer'
import type GamificationEventTransformer from '#transformers/gamification_event_transformer'
import type InsuranceBillingTransformer from '#transformers/insurance_billing_transformer'
import type LevelTransformer from '#transformers/level_transformer'
import type NotificationTransformer from '#transformers/notification_transformer'
import type OccurrenceTransformer from '#transformers/occurrence_transformer'
import type PostTransformer from '#transformers/post_transformer'
import type PurchaseRequestTransformer from '#transformers/purchase_request_transformer'
import type ResponsibleAddressTransformer from '#transformers/responsible_address_transformer'
import type RoleTransformer from '#transformers/role_transformer'
import type ScholarshipTransformer from '#transformers/scholarship_transformer'
import type SchoolAchievementConfigTransformer from '#transformers/school_achievement_config_transformer'
import type SchoolChainTransformer from '#transformers/school_chain_transformer'
import type SchoolGroupTransformer from '#transformers/school_group_transformer'
import type SchoolPartnerTransformer from '#transformers/school_partner_transformer'
import type SchoolTransformer from '#transformers/school_transformer'
import type StoreInstallmentRuleTransformer from '#transformers/store_installment_rule_transformer'
import type StoreItemTransformer from '#transformers/store_item_transformer'
import type StoreOrderItemTransformer from '#transformers/store_order_item_transformer'
import type StoreOrderTransformer from '#transformers/store_order_transformer'
import type StoreSettlementTransformer from '#transformers/store_settlement_transformer'
import type StoreTransformer from '#transformers/store_transformer'
import type StudentAddressTransformer from '#transformers/student_address_transformer'
import type StudentBalanceTransactionTransformer from '#transformers/student_balance_transaction_transformer'
import type StudentDocumentTransformer from '#transformers/student_document_transformer'
import type StudentEmergencyContactTransformer from '#transformers/student_emergency_contact_transformer'
import type StudentGamificationTransformer from '#transformers/student_gamification_transformer'
import type StudentHasAssignmentTransformer from '#transformers/student_has_assignment_transformer'
import type StudentHasAttendanceTransformer from '#transformers/student_has_attendance_transformer'
import type StudentHasLevelTransformer from '#transformers/student_has_level_transformer'
import type StudentHasResponsibleTransformer from '#transformers/student_has_responsible_transformer'
import type StudentMedicalInfoTransformer from '#transformers/student_medical_info_transformer'
import type StudentPaymentTransformer from '#transformers/student_payment_transformer'
import type StudentTransformer from '#transformers/student_transformer'
import type SubjectTransformer from '#transformers/subject_transformer'
import type TeacherHasClassTransformer from '#transformers/teacher_has_class_transformer'
import type TeacherTransformer from '#transformers/teacher_transformer'
import type UserHasSchoolGroupTransformer from '#transformers/user_has_school_group_transformer'
import type UserHasSchoolTransformer from '#transformers/user_has_school_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type LevelAssignedToCourseHasAcademicPeriodTransformer from '#transformers/level_assigned_to_course_has_academic_period_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type AcademicPeriod = InferData<AcademicPeriodTransformer>
  export namespace AcademicPeriod {
    export type Variants = InferVariants<AcademicPeriodTransformer>
  }
  export type Achievement = InferData<AchievementTransformer>
  export namespace Achievement {
    export type Variants = InferVariants<AchievementTransformer>
  }
  export type Assignment = InferData<AssignmentTransformer>
  export namespace Assignment {
    export type Variants = InferVariants<AssignmentTransformer>
  }
  export type Attendance = InferData<AttendanceTransformer>
  export namespace Attendance {
    export type Variants = InferVariants<AttendanceTransformer>
  }
  export type CalendarSlot = InferData<CalendarSlotTransformer>
  export namespace CalendarSlot {
    export type Variants = InferVariants<CalendarSlotTransformer>
  }
  export type CanteenItem = InferData<CanteenItemTransformer>
  export namespace CanteenItem {
    export type Variants = InferVariants<CanteenItemTransformer>
  }
  export type CanteenMealReservation = InferData<CanteenMealReservationTransformer>
  export namespace CanteenMealReservation {
    export type Variants = InferVariants<CanteenMealReservationTransformer>
  }
  export type CanteenMeal = InferData<CanteenMealTransformer>
  export namespace CanteenMeal {
    export type Variants = InferVariants<CanteenMealTransformer>
  }
  export type CanteenMonthlyTransfer = InferData<CanteenMonthlyTransferTransformer>
  export namespace CanteenMonthlyTransfer {
    export type Variants = InferVariants<CanteenMonthlyTransferTransformer>
  }
  export type CanteenPurchase = InferData<CanteenPurchaseTransformer>
  export namespace CanteenPurchase {
    export type Variants = InferVariants<CanteenPurchaseTransformer>
  }
  export type Canteen = InferData<CanteenTransformer>
  export namespace Canteen {
    export type Variants = InferVariants<CanteenTransformer>
  }
  export type Challenge = InferData<ChallengeTransformer>
  export namespace Challenge {
    export type Variants = InferVariants<ChallengeTransformer>
  }
  export type Class = InferData<ClassTransformer>
  export namespace Class {
    export type Variants = InferVariants<ClassTransformer>
  }
  export type Comment = InferData<CommentTransformer>
  export namespace Comment {
    export type Variants = InferVariants<CommentTransformer>
  }
  export type ContractDocument = InferData<ContractDocumentTransformer>
  export namespace ContractDocument {
    export type Variants = InferVariants<ContractDocumentTransformer>
  }
  export type ContractEarlyDiscount = InferData<ContractEarlyDiscountTransformer>
  export namespace ContractEarlyDiscount {
    export type Variants = InferVariants<ContractEarlyDiscountTransformer>
  }
  export type ContractInterestConfig = InferData<ContractInterestConfigTransformer>
  export namespace ContractInterestConfig {
    export type Variants = InferVariants<ContractInterestConfigTransformer>
  }
  export type ContractPaymentDay = InferData<ContractPaymentDayTransformer>
  export namespace ContractPaymentDay {
    export type Variants = InferVariants<ContractPaymentDayTransformer>
  }
  export type Contract = InferData<ContractTransformer>
  export namespace Contract {
    export type Variants = InferVariants<ContractTransformer>
  }
  export type CourseHasAcademicPeriod = InferData<CourseHasAcademicPeriodTransformer>
  export namespace CourseHasAcademicPeriod {
    export type Variants = InferVariants<CourseHasAcademicPeriodTransformer>
  }
  export type Course = InferData<CourseTransformer>
  export namespace Course {
    export type Variants = InferVariants<CourseTransformer>
  }
  export type EventParticipant = InferData<EventParticipantTransformer>
  export namespace EventParticipant {
    export type Variants = InferVariants<EventParticipantTransformer>
  }
  export type Event = InferData<EventTransformer>
  export namespace Event {
    export type Variants = InferVariants<EventTransformer>
  }
  export type ExamGrade = InferData<ExamGradeTransformer>
  export namespace ExamGrade {
    export type Variants = InferVariants<ExamGradeTransformer>
  }
  export type Exam = InferData<ExamTransformer>
  export namespace Exam {
    export type Variants = InferVariants<ExamTransformer>
  }
  export type GamificationEvent = InferData<GamificationEventTransformer>
  export namespace GamificationEvent {
    export type Variants = InferVariants<GamificationEventTransformer>
  }
  export type InsuranceBilling = InferData<InsuranceBillingTransformer>
  export namespace InsuranceBilling {
    export type Variants = InferVariants<InsuranceBillingTransformer>
  }
  export type Level = InferData<LevelTransformer>
  export namespace Level {
    export type Variants = InferVariants<LevelTransformer>
  }
  export type Notification = InferData<NotificationTransformer>
  export namespace Notification {
    export type Variants = InferVariants<NotificationTransformer>
  }
  export type Occurrence = InferData<OccurrenceTransformer>
  export namespace Occurrence {
    export type Variants = InferVariants<OccurrenceTransformer>
  }
  export type Post = InferData<PostTransformer>
  export namespace Post {
    export type Variants = InferVariants<PostTransformer>
  }
  export type PurchaseRequest = InferData<PurchaseRequestTransformer>
  export namespace PurchaseRequest {
    export type Variants = InferVariants<PurchaseRequestTransformer>
  }
  export type ResponsibleAddress = InferData<ResponsibleAddressTransformer>
  export namespace ResponsibleAddress {
    export type Variants = InferVariants<ResponsibleAddressTransformer>
  }
  export type Role = InferData<RoleTransformer>
  export namespace Role {
    export type Variants = InferVariants<RoleTransformer>
  }
  export type Scholarship = InferData<ScholarshipTransformer>
  export namespace Scholarship {
    export type Variants = InferVariants<ScholarshipTransformer>
  }
  export type SchoolAchievementConfig = InferData<SchoolAchievementConfigTransformer>
  export namespace SchoolAchievementConfig {
    export type Variants = InferVariants<SchoolAchievementConfigTransformer>
  }
  export type SchoolChain = InferData<SchoolChainTransformer>
  export namespace SchoolChain {
    export type Variants = InferVariants<SchoolChainTransformer>
  }
  export type SchoolGroup = InferData<SchoolGroupTransformer>
  export namespace SchoolGroup {
    export type Variants = InferVariants<SchoolGroupTransformer>
  }
  export type SchoolPartner = InferData<SchoolPartnerTransformer>
  export namespace SchoolPartner {
    export type Variants = InferVariants<SchoolPartnerTransformer>
  }
  export type School = InferData<SchoolTransformer>
  export namespace School {
    export type Variants = InferVariants<SchoolTransformer>
  }
  export type StoreInstallmentRule = InferData<StoreInstallmentRuleTransformer>
  export namespace StoreInstallmentRule {
    export type Variants = InferVariants<StoreInstallmentRuleTransformer>
  }
  export type StoreItem = InferData<StoreItemTransformer>
  export namespace StoreItem {
    export type Variants = InferVariants<StoreItemTransformer>
  }
  export type StoreOrderItem = InferData<StoreOrderItemTransformer>
  export namespace StoreOrderItem {
    export type Variants = InferVariants<StoreOrderItemTransformer>
  }
  export type StoreOrder = InferData<StoreOrderTransformer>
  export namespace StoreOrder {
    export type Variants = InferVariants<StoreOrderTransformer>
  }
  export type StoreSettlement = InferData<StoreSettlementTransformer>
  export namespace StoreSettlement {
    export type Variants = InferVariants<StoreSettlementTransformer>
  }
  export type Store = InferData<StoreTransformer>
  export namespace Store {
    export type Variants = InferVariants<StoreTransformer>
  }
  export type StudentAddress = InferData<StudentAddressTransformer>
  export namespace StudentAddress {
    export type Variants = InferVariants<StudentAddressTransformer>
  }
  export type StudentBalanceTransaction = InferData<StudentBalanceTransactionTransformer>
  export namespace StudentBalanceTransaction {
    export type Variants = InferVariants<StudentBalanceTransactionTransformer>
  }
  export type StudentDocument = InferData<StudentDocumentTransformer>
  export namespace StudentDocument {
    export type Variants = InferVariants<StudentDocumentTransformer>
  }
  export type StudentEmergencyContact = InferData<StudentEmergencyContactTransformer>
  export namespace StudentEmergencyContact {
    export type Variants = InferVariants<StudentEmergencyContactTransformer>
  }
  export type StudentGamification = InferData<StudentGamificationTransformer>
  export namespace StudentGamification {
    export type Variants = InferVariants<StudentGamificationTransformer>
  }
  export type StudentHasAssignment = InferData<StudentHasAssignmentTransformer>
  export namespace StudentHasAssignment {
    export type Variants = InferVariants<StudentHasAssignmentTransformer>
  }
  export type StudentHasAttendance = InferData<StudentHasAttendanceTransformer>
  export namespace StudentHasAttendance {
    export type Variants = InferVariants<StudentHasAttendanceTransformer>
  }
  export type StudentHasLevel = InferData<StudentHasLevelTransformer>
  export namespace StudentHasLevel {
    export type Variants = InferVariants<StudentHasLevelTransformer>
  }
  export type StudentHasResponsible = InferData<StudentHasResponsibleTransformer>
  export namespace StudentHasResponsible {
    export type Variants = InferVariants<StudentHasResponsibleTransformer>
  }
  export type StudentMedicalInfo = InferData<StudentMedicalInfoTransformer>
  export namespace StudentMedicalInfo {
    export type Variants = InferVariants<StudentMedicalInfoTransformer>
  }
  export type StudentPayment = InferData<StudentPaymentTransformer>
  export namespace StudentPayment {
    export type Variants = InferVariants<StudentPaymentTransformer>
  }
  export type Student = InferData<StudentTransformer>
  export namespace Student {
    export type Variants = InferVariants<StudentTransformer>
  }
  export type Subject = InferData<SubjectTransformer>
  export namespace Subject {
    export type Variants = InferVariants<SubjectTransformer>
  }
  export type TeacherHasClass = InferData<TeacherHasClassTransformer>
  export namespace TeacherHasClass {
    export type Variants = InferVariants<TeacherHasClassTransformer>
  }
  export type Teacher = InferData<TeacherTransformer>
  export namespace Teacher {
    export type Variants = InferVariants<TeacherTransformer>
  }
  export type UserHasSchoolGroup = InferData<UserHasSchoolGroupTransformer>
  export namespace UserHasSchoolGroup {
    export type Variants = InferVariants<UserHasSchoolGroupTransformer>
  }
  export type UserHasSchool = InferData<UserHasSchoolTransformer>
  export namespace UserHasSchool {
    export type Variants = InferVariants<UserHasSchoolTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type LevelAssignedToCourseHasAcademicPeriod =
    InferData<LevelAssignedToCourseHasAcademicPeriodTransformer>
  export namespace LevelAssignedToCourseHasAcademicPeriod {
    export type Variants = InferVariants<LevelAssignedToCourseHasAcademicPeriodTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
