import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'SchoolGroup'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.text('id').primary()
      table.timestamp('createdAt').notNullable().defaultTo(this.now())
      table.timestamp('updatedAt').notNullable()
      table.text('name').notNullable()
      table
        .text('schoolChainId')
        .notNullable()
        .references('id')
        .inTable('SchoolChain')
        .onUpdate('CASCADE')
        .onDelete('RESTRICT')
      table.specificType('type', '"SchoolGroupType"').notNullable()
      table.boolean('isAutoGenerated').notNullable().defaultTo(false)
      table.boolean('hasInsurance').nullable()
      table.float('insurancePercentage', 8).nullable()
      table.float('insuranceCoveragePercentage', 8).nullable()
      table.integer('insuranceClaimWaitingDays').nullable()
      table.index(['schoolChainId'])
      table.index(['type'])
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
