import { BaseModelDto } from '@adocasts.com/dto/base'
import type SchoolGroup from '#models/school_group'
import type { SchoolGroupType } from '#models/school_group'
import type { DateTime } from 'luxon'
import SchoolChainDto from './school_chain.dto.js'

export default class SchoolGroupDto extends BaseModelDto {
  declare id: string
  declare name: string
  declare type: SchoolGroupType
  declare isAutoGenerated: boolean
  declare hasInsurance: boolean | null
  declare insurancePercentage: number | null
  declare insuranceCoveragePercentage: number | null
  declare insuranceClaimWaitingDays: number | null
  declare schoolChainId: string
  declare createdAt: DateTime
  declare updatedAt: DateTime | null
  declare schoolChain?: SchoolChainDto

  constructor(model?: SchoolGroup) {
    super()

    if (!model) return

    this.id = model.id
    this.name = model.name
    this.type = model.type
    this.isAutoGenerated = model.isAutoGenerated
    this.hasInsurance = model.hasInsurance
    this.insurancePercentage = model.insurancePercentage
    this.insuranceCoveragePercentage = model.insuranceCoveragePercentage
    this.insuranceClaimWaitingDays = model.insuranceClaimWaitingDays
    this.schoolChainId = model.schoolChainId
    this.createdAt = model.createdAt
    this.updatedAt = model.updatedAt
    this.schoolChain = model.schoolChain ? new SchoolChainDto(model.schoolChain) : undefined
  }
}
