import { DateTime } from 'luxon'
import { BaseModel, column, belongsTo, hasMany, manyToMany } from '@adonisjs/lucid/orm'
import type { BelongsTo, HasMany, ManyToMany } from '@adonisjs/lucid/types/relations'
import SchoolChain from './school_chain.js'
import School from './school.js'
import UserHasSchoolGroup from './user_has_school_group.js'

export type SchoolGroupType = 'CITY' | 'STATE' | 'CUSTOM'

export default class SchoolGroup extends BaseModel {
  static table = 'SchoolGroup'

  @column({ isPrimary: true })
  declare id: string

  @column()
  declare name: string

  @column()
  declare type: SchoolGroupType

  @column()
  declare isAutoGenerated: boolean

  // Insurance config
  @column()
  declare hasInsurance: boolean | null

  @column()
  declare insurancePercentage: number | null

  @column()
  declare insuranceCoveragePercentage: number | null

  @column()
  declare insuranceClaimWaitingDays: number | null

  // Foreign keys
  @column()
  declare schoolChainId: string

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null

  // Relationships
  @belongsTo(() => SchoolChain, { foreignKey: 'schoolChainId' })
  declare schoolChain: BelongsTo<typeof SchoolChain>

  @manyToMany(() => School, {
    pivotTable: 'SchoolHasGroup',
    localKey: 'id',
    pivotForeignKey: 'school_group_id',
    relatedKey: 'id',
    pivotRelatedForeignKey: 'school_id',
  })
  declare schools: ManyToMany<typeof School>

  @hasMany(() => UserHasSchoolGroup, { foreignKey: 'schoolGroupId' })
  declare userHasSchoolGroups: HasMany<typeof UserHasSchoolGroup>
}
